### ISSUE TITLE
Future UI features/improvements (whiteboard picture)

### ISSUE THREAD

**Issue by mbsr-nuna** [ConservationInternational/ShinyCam#37]
Below, I'm pasting a picture of the whiteboard from 6/10/17 with RShiny features that are done, in progress, and to be developed ("TBD").

This should be split into multiple issues (maybe after scoping/prioritizing), but I wanted to park it somewhere.

![2017_06_10_rshiny_future](https://user-images.githubusercontent.com/22922012/27006628-bc968f1c-4ded-11e7-90a7-615335d13035.JPG)

**Comment by teamcoders-ehf** [comment]
cleaning up and removing for now
