### ISSUE TITLE
Rearrange UI features in interactive map.

### ISSUE THREAD

**Issue by sewardlee337** [ConservationInternational/ShinyCam#40]
**Problem:** Graphs under the `Interactive Map` tab are currently squeezed into the right-hand panel, and are thus too small.

**Desired solution:** Move the graphs to a new row below the Leaflet map, so that they can use the space below the map rather than just the right-hand panel. 

For example, see: https://shiny.rstudio.com/gallery/plot-plus-three-columns.html

**Comment by teamcoders-ehf** [comment]
completed
